### CONTENTS
- Data Science Life Cycle
- Data Science Libraries

### DataScience Life Cycle

##### Steps
- 1. Business Understsanding
- 2. Data Preparation
- 3. Data Munging/Data Wrangling
        - feature selection
        - EDA tools
- 4. Model training
- 5. Model Evaluation
- 6. Model Deployment
- 7. Model Tracking

### Data Science Process

- collection,cleaning -> Data Engineers

- cleaning, Exploratory Analysis -> Data Analysts

- Building Model,Model Deployment ->ML Engineers

- All the Above -> Data Scientists

#### Data Analysis Libraries 

- Numpy
- Pandas
- Matplotlib
- Seaborn
- scipy


### Numpy
- Numerical python
- Developed in 2005 by Travis oliphant
- Create Arrays
     - 0D Array
     - 1d Array
     - 2d Array
     - Multi Dimensional
- Linear Algebra,Fourier transform,matrices

In [1]:
import numpy as np

In [4]:
# to check for version
np.__version__

'1.18.5'

#### Creating arrays

In [12]:
x=np.array(51)
x

array(51)

In [13]:
np.ndim(x)

0

In [14]:
# 1d array
x1=np.array([1,2,3,4,5,6])
x1

array([1, 2, 3, 4, 5, 6])

In [15]:
np.ndim(x1)

1

In [17]:
# 2d array
x2 =np.array([[1,2,3],[4,5,6]])
print(x2)
print(np.ndim(x2))

[[1 2 3]
 [4 5 6]]
2


In [18]:
# to get number of elements
np.size(x2)

6

In [19]:
# to get rows and cols
np.shape(x2)

(2, 3)

In [21]:
### 3d array

x3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x3)
print(np.ndim(x3))
print(np.size(x3))
print(np.shape(x3))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3
12
(1, 3, 4)


##### Methods to create arrays
- Zeroes
- ones
- linspace
- logspace
- arange
- random

In [25]:
a = np.zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
a = np.zeros(4,dtype=int)
print(a)

[0 0 0 0]


In [27]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [31]:
a1 = np.ones(5,dtype=int)
print(a1)

[1 1 1 1 1]


In [36]:
a1 = np.ones(5,dtype=int)
print(a1)
a2 = a1.reshape(1,5)
print(a2)
a3 = a1.reshape(5,1)
print(a3)

[1 1 1 1 1]
[[1 1 1 1 1]]
[[1]
 [1]
 [1]
 [1]
 [1]]


In [41]:
a = np.arange(1,12,2)
print(a)
print(np.ndim(a))
print(np.size(a))


[ 1  3  5  7  9 11]
1
6


In [43]:
a1 = a.reshape(2,3)
a1

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [46]:
# logspace

l1 = np.logspace(1,5)# by default num=50
l1

array([1.00000000e+01, 1.20679264e+01, 1.45634848e+01, 1.75751062e+01,
       2.12095089e+01, 2.55954792e+01, 3.08884360e+01, 3.72759372e+01,
       4.49843267e+01, 5.42867544e+01, 6.55128557e+01, 7.90604321e+01,
       9.54095476e+01, 1.15139540e+02, 1.38949549e+02, 1.67683294e+02,
       2.02358965e+02, 2.44205309e+02, 2.94705170e+02, 3.55648031e+02,
       4.29193426e+02, 5.17947468e+02, 6.25055193e+02, 7.54312006e+02,
       9.10298178e+02, 1.09854114e+03, 1.32571137e+03, 1.59985872e+03,
       1.93069773e+03, 2.32995181e+03, 2.81176870e+03, 3.39322177e+03,
       4.09491506e+03, 4.94171336e+03, 5.96362332e+03, 7.19685673e+03,
       8.68511374e+03, 1.04811313e+04, 1.26485522e+04, 1.52641797e+04,
       1.84206997e+04, 2.22299648e+04, 2.68269580e+04, 3.23745754e+04,
       3.90693994e+04, 4.71486636e+04, 5.68986603e+04, 6.86648845e+04,
       8.28642773e+04, 1.00000000e+05])

In [47]:
l1 = np.logspace(1,5,3)
l1

array([1.e+01, 1.e+03, 1.e+05])

In [51]:
# linspace
l = np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [63]:
# random
r = np.random.randn(1,10)
r

array([[-0.56467052,  0.42673198, -0.99541839,  1.37912282,  0.05412184,
         1.97718516,  0.60455686, -0.28448204, -0.82964614, -1.26077803]])

In [64]:
np.ndim(r)

2

In [67]:
r3=r.flatten()
print(r3)
print(np.ndim(r3))

[-0.56467052  0.42673198 -0.99541839  1.37912282  0.05412184  1.97718516
  0.60455686 -0.28448204 -0.82964614 -1.26077803]
1


In [68]:
r1 = np.random.randint(1,100,6)
r1

array([61, 99, 83, 94, 33, 11])

### Accessing elements
- Indexing
   - +ve
   - -ve
- slicing
    - [strat:stop:step]
- looping
     - for
     - while