### CONTENTS

- Regression
- Linear Regression

- Classification
     - Bionomial ----> T or F,P or F,0 or 1
     - Multinomial ----> 0,1,2,3

- Logistic Regression
    - uses sigmoid function whiles b/w o and 1
    - sigmoid function y=1/1+e^-z

In [11]:
import pandas as pd

In [43]:
df = pd.read_csv("https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Classification/Heart_disease.csv")
df.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No

In [44]:
df.isna().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [45]:
df["AHD"].unique()

array(['No', 'Yes'], dtype=object)

In [46]:
df["Thal"].unique()

array(['fixed', 'normal', 'reversable', nan], dtype=object)

In [47]:
import numpy as np

In [48]:
df["Thal"].replace(np.nan,"fixed",inplace=True)
df["Ca"].replace(np.nan,"0.0",inplace=True)

In [49]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [50]:
df

Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
0     63    1       typical     145   233    1        2    150      0   
1     67    1  asymptomatic     160   286    0        2    108      1   
2     67    1  asymptomatic     120   229    0        2    129      1   
3     37    1    nonanginal     130   250    0        0    187      0   
4     41    0    nontypical     130   204    0        2    172      0   
..   ...  ...           ...     ...   ...  ...      ...    ...    ...   
298   45    1       typical     110   264    0        0    132      0   
299   68    1  asymptomatic     144   193    1        0    141      0   
300   57    1  asymptomatic     130   131    0        0    115      1   
301   57    0    nontypical     130   236    0        2    174      0   
302   38    1    nonanginal     138   175    0        0    173      0   

     Oldpeak  Slope   Ca        Thal  AHD  
0        2.3      3    0       fixed   No  
1        1.5      2    3      normal  Yes  
2        2.6      2    2  reversable  Yes  
3        3.5      3    0      normal   No  
4        1.4      1    0      normal   No  
..       ...    ...  ...         ...  ...  
298      1.2      2    0  reversable  Yes  
299      3.4      2    2  reversable  Yes  
300      1.2      2    1  reversable  Yes  
301      0.0      2    1      normal  Yes  
302      0.0      1  0.0      normal   No  

[303 rows x 14 columns]

In [51]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
df['Thal'] = label.fit_transform(df["Thal"])
df["ChestPain"]=label.fit_transform(df["ChestPain"])
df["AHD"]=label.fit_transform(df["AHD"])

In [52]:
df.head()

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0   63    1          3     145   233    1        2    150      0      2.3   
1   67    1          0     160   286    0        2    108      1      1.5   
2   67    1          0     120   229    0        2    129      1      2.6   
3   37    1          1     130   250    0        0    187      0      3.5   
4   41    0          2     130   204    0        2    172      0      1.4   

   Slope Ca  Thal  AHD  
0      3  0     0    0  
1      2  3     1    1  
2      2  2     2    1  
3      3  0     1    0  
4      1  0     1    0

In [53]:
x = df.drop("AHD",axis=1)
y = df["AHD"]

In [54]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.3,random_state=25)


In [55]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

C:\Users\sravani\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [56]:
model.predict([[67,1,0,120,229,0,2,129,1,2.6,2,2,2]])

array([1])

In [57]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1])

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Age        303 non-null    int64  
 1   Sex        303 non-null    int64  
 2   ChestPain  303 non-null    int32  
 3   RestBP     303 non-null    int64  
 4   Chol       303 non-null    int64  
 5   Fbs        303 non-null    int64  
 6   RestECG    303 non-null    int64  
 7   MaxHR      303 non-null    int64  
 8   ExAng      303 non-null    int64  
 9   Oldpeak    303 non-null    float64
 10  Slope      303 non-null    int64  
 11  Ca         303 non-null    object 
 12  Thal       303 non-null    int32  
 13  AHD        303 non-null    int32  
dtypes: float64(1), int32(3), int64(9), object(1)
memory usage: 29.7+ KB


In [59]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

85.91549295774648

In [60]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[105,  12],
       [ 18,  78]], dtype=int64)

In [61]:
# Accuracy = TP+TN/TP+FP+fN+TN


In [63]:
df["AHD"].value_counts()

0    164
1    139
Name: AHD, dtype: int64

0--->300
1---->200
- balanced data set
500
yes--->400
no--->100
- imbalanced dataset
- metrics we use are 
    - precision
    - recall